version: "3.9"

services:
  web:
    image: nginx
    ports:
    - "80:80"

  mdns-docker:
    build: .
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket